### ISSUE TITLE
pip install NiftyPET error

### ISSUE THREAD

**Issue by leomarec** [pjmark/NiftyPET#11]
Dear NiftyPET,

We have been trying to install NiftyPET and everything appears to go well except for when we ready the pip install niftyPET section.

Installation of NiftyPET by `pip install niftypet` fails with the following error:
Failed to build pydcm2niix
ERROR: Could not build wheels for pydcm2niix which use PEP 517 and cannot be installed directly
The conda (v3-2021.11; Linux) environment utilizes python 3.9.7 and was created as shown below:  
`conda create -n mbl_niftypet python=3.9`
We installed the following packages before trying to install niftypet:
`conda install -c conda-forge python=3.9 numpy scipy scikit-image matplotlib nibabel pydicom`
`conda install -c conda-forge python=3.9 ipykernel ipywidgets`
The outputs for the entire sequence (stdout and stderr) are in the attached document.
[niftypet.txt](https://github.com/NiftyPET/NiftyPET/files/8026762/niftypet.txt)

Thank you for your help with this matter.

Sincerly,

Leo Marecki

**Comment by casperdcl** [comment]
Hmm I can't see any debugging info in the log.

Could you try `pip install --log=log.txt pydcm2niix` and upload the resulting `log.txt` file?

**Comment by leomarec** [comment]
Dear Casper,

I ran the installation and attached is the `log.txt` file you requested

[log.txt](https://github.com/NiftyPET/NiftyPET/files/8027269/log.txt)

Thank you for getting back to us so quickly.

Sincerely,

Leo Marecki

**Comment by casperdcl** [comment]
The error says `libstdc++.a` is missing. Looks like it's been reported before (https://github.com/rordenlab/dcm2niix/issues/450 & https://github.com/rordenlab/dcm2niix/issues/137). Depending on your OS you could try:

- `sudo yum install libstdc++-static`, or
- `sudo apt-get update && sudo apt-get install build-essential g++`

**Comment by leomarec** [comment]
In the environment we ran the code
`g++ --version`
and received the output as stated in the attached text file.
Additionally, when we run
`pip install brainweb`  # basic registration
`pip install spm12`     # MATLAB-based registration
we do not get this issue
[complier.txt](https://github.com/NiftyPET/NiftyPET/files/8033532/complier.txt)

**Comment by casperdcl** [comment]
Hey @leomarec I edited my last comment a few times - did you see the recommendations in the [last version](https://github.com/NiftyPET/NiftyPET/issues/11#issuecomment-1033102472)?

**Comment by leomarec** [comment]
Dear Casper,

We need to know if `sudo yum install libstdc++-static`  will be utilized by the compute nodes when we run jobs or is it only for the installation.

Thank you for the help,

Leo Marecki

**Comment by casperdcl** [comment]
Should only be needed for install.

**Comment by leomarec** [comment]
Dear Casper,

Thank you for your help with this.

We have been able to install it with no errors.

Sincerely,

Leo Marecki

**Comment by casperdcl** [comment]
great, happy to help
